strash
write_bench -l /home/abc586/ABC_BENCH_GRAPHS/aes/aes_orig.bench
refactor
balance
balance
refactor -z
refactor -z
refactor -z
refactor -z
resub -z
refactor -z
refactor
rewrite
rewrite -z
rewrite -z
rewrite -z
balance
refactor -z
rewrite
rewrite -z
refactor -z
refactor
write_bench -l /home/abc586/ABC_BENCH_GRAPHS/aes/aes_syn141.bench
dch
map -B 0.9
topo
stime -c
buffer -c
upsize -c
dnsize -c
