strash
write_bench -l /home/abc586/ABC_BENCH_GRAPHS/aes/aes_orig.bench
refactor -z
rewrite -z
refactor -z
refactor -z
resub -z
refactor
resub -z
refactor
refactor -z
refactor
refactor -z
refactor -z
rewrite
rewrite
refactor -z
rewrite
refactor
refactor -z
resub -z
refactor -z
write_bench -l /home/abc586/ABC_BENCH_GRAPHS/aes/aes_syn1063.bench
dch
map -B 0.9
topo
stime -c
buffer -c
upsize -c
dnsize -c
