strash
write_bench -l /home/abc586/ABC_BENCH_GRAPHS/aes/aes_orig.bench
refactor
refactor
balance
refactor -z
resub -z
refactor -z
balance
refactor
rewrite
refactor -z
refactor -z
resub
refactor -z
refactor -z
refactor -z
refactor -z
refactor -z
refactor
refactor -z
balance
write_bench -l /home/abc586/ABC_BENCH_GRAPHS/aes/aes_syn1410.bench
dch
map -B 0.9
topo
stime -c
buffer -c
upsize -c
dnsize -c
