strash
write_bench -l /home/abc586/ABC_BENCH_GRAPHS/aes/aes_orig.bench
refactor -z
balance
refactor -z
rewrite -z
resub -z
refactor -z
resub -z
rewrite -z
rewrite -z
refactor -z
refactor
resub -z
rewrite
resub -z
refactor -z
refactor
refactor -z
resub -z
refactor
rewrite -z
write_bench -l /home/abc586/ABC_BENCH_GRAPHS/aes/aes_syn637.bench
dch
map -B 0.9
topo
stime -c
buffer -c
upsize -c
dnsize -c
